# Generated by Django 3.1.7 on 2021-02-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Outages',
            fields=[
                ('OutageID', models.AutoField(primary_key=True, serialize=False)),
                ('ActivityType', models.BooleanField(verbose_name=False)),
                ('OutageStartTime', models.DateTimeField()),
                ('OutageEndTime', models.DateTimeField()),
                ('OutageDuration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProdURL',
            fields=[
                ('PLinkID', models.AutoField(primary_key=True, serialize=False)),
                ('ProdLink', models.CharField(max_length=100)),
            ],
        ),
    ]
