# Generated by Django 3.1.7 on 2021-02-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Downtimetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outages',
            name='Outageremarks',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
